# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  secrets-in-github-actions:
    runs-on: windows-latest
    steps:
      - name: step1
        env:
          CHANNEL_ACCESS_TOKEN: ${{secrets.CHANNEL_ACCESS_TOKEN}}
          CHANNEL_SECRET: ${{CHANNEL_SECRET}}
        
